create extension if not exists pgcrypto;
create table public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null,
  city text not null,
  objective text not null,
  instagram text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, instagram)
);
create table public.audit_snapshots (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score between 0 and 100),
  answers jsonb not null,
  categories jsonb not null,
  recommendations jsonb not null,
  audited_at timestamptz not null default now()
);
create table public.content_ideas (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id bigint not null,
  format text not null check (format in ('Reel', 'Carrusel', 'Historia')),
  goal text not null check (goal in ('Atraer', 'Educar', 'Vender', 'Fidelizar')),
  title text not null,
  hook text not null,
  script text not null,
  caption text not null,
  hashtags text not null,
  reason text not null,
  potential integer not null check (potential between 0 and 100),
  color text not null,
  saved boolean not null default false,
  created_at timestamptz not null default now(),
  unique (business_id, client_id)
);
create table public.planned_content (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id bigint not null,
  week_offset integer not null default 0,
  day_index integer not null check (day_index between 0 and 6),
  publish_time text not null,
  format text not null check (format in ('Reel', 'Carrusel', 'Historia')),
  title text not null,
  status text not null check (status in ('Idea', 'Borrador', 'Listo', 'Publicado')),
  color text not null,
  unique (business_id, client_id)
);
create index businesses_owner_idx on public.businesses(owner_id);
create index audit_snapshots_business_idx on public.audit_snapshots(business_id, audited_at desc);
create index content_ideas_business_idx on public.content_ideas(business_id, created_at desc);
create index planned_content_business_idx on public.planned_content(business_id, week_offset, day_index);
alter table public.businesses enable row level security;
alter table public.audit_snapshots enable row level security;
alter table public.content_ideas enable row level security;
alter table public.planned_content enable row level security;
create policy "owners manage their businesses" on public.businesses
  for all to authenticated using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "owners manage their audits" on public.audit_snapshots
  for all to authenticated using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "owners manage their ideas" on public.content_ideas
  for all to authenticated using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "owners manage their calendar" on public.planned_content
  for all to authenticated using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
